- name: Copy file over
  copy:
    src: artifact.tar.gz
    dest: /tmp
- name: Deploy backend
  shell: |
    mkdir /app/
    cd /app
    tar -xf /tmp/artifact.tar.gz
    printenv | tee current-env
    npm install
    pm2 stop default
    pm2 start npm -- start
